/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in many projects and kept here so plain
// TypeScript project references work before the first local Next run.
